# Generated by Django 4.2.1 on 2023-07-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNba', '0002_equipos_post_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consultar'], [1, 'reclamar'], [2, 'sugerir'], [3, 'felicitar']])),
                ('numero', models.IntegerField()),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
